CREATE TABLE IF NOT EXISTS domains.attribute
(
  id CHAR(36) PRIMARY KEY,
  code VARCHAR(4096) NULL,
  origin VARCHAR(50) NULL,
  kind VARCHAR(50) NOT NULL,
  description VARCHAR(4096) NULL,
  name VARCHAR(4096) NULL,
  creation_time TIMESTAMP NOT NULL
)
BACKUP NO
DISTSTYLE AUTO SORTKEY AUTO ENCODE AUTO;
